### PR TITLE
Feat: Make the HTMX object available in templates as a global context

### PR DESCRIPTION
**Pull request by devbijay**
FIX: #26

### CODE REVIEW

**Comment by edmondchuc** [comment]
@sponsfreixes any comments on this one?

**Comment by stfnx** [comment]
Hey, may I ask why this isn't merged yet?

**Comment by edmondchuc** [comment]
I was waiting to see if @sponsfreixes would like to take a look and comment on anything. If not, I can merge this soon (within the week).

@stfnx do you have any use cases where you need access to the htmx object in the templates context? It'd be good to get some info on the use cases and add it to the docs.

**Comment by sponsfreixes** [comment]
Looks good to me! Maybe we should add a comment to the documentation so that users know it exists.

**Review by sponsfreixes — APPROVED** [review]

**Pull request merged**
